### ISSUE TITLE
Exception: Process executed too fast to gather energy consumption

### ISSUE THREAD

**Issue by NSVR57** [responsibleproblemsolving/energy-usage#11]
Hi 

I am trying to find the power consumption for deep learning inference. I am using Intel Dev cloud for inferencing on FPGA device. but I am getting the following error.

I have called like this:
```

if __name__ == '__main__':
    sys.exit(energyusage.evaluate(main() or 0))

```

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/u50737/.local/lib/python3.6/site-packages/energyusage/evaluate.py", line 22, in func
    value = user_func(*args)
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "Image_classification.py", line 182, in <module>
    sys.exit(energyusage.evaluate(main() or 0))
  File "/home/u50737/.local/lib/python3.6/site-packages/energyusage/evaluate.py", line 314, in evaluate
    printToScreen = printToScreen)
  File "/home/u50737/.local/lib/python3.6/site-packages/energyusage/evaluate.py", line 115, in energy
    raise Exception("Process executed too fast to gather energy consumption")
Exception: Process executed too fast to gather energy consumption
```

**Comment by NSVR57** [comment]
I understand my mistake. it was resolved.
