### ISSUE TITLE
For processes that don't run very long the `evaluate` call fails.

### ISSUE THREAD

**Issue by alexmherrmann** [responsibleproblemsolving/energy-usage#2]
For small run times, the `evaluate` function falls apart with the below error. It looks like the RAPLfiles written out may not contain the correct format but there are very little comments within the body of many of these functions so I'm just guessing based off of a few cursory glances. This makes it very difficult to plot a progression of complexity. If there is a requirement of some amount of runtime it would be nice to have a rich error rather than letting the python statistics package catch and exit.

```
Traceback (most recent call last):
  File "/home/alex/git/mine/private/school/4150/energyusage/PS12.py", line 62, in <module>
    main()
  File "/home/alex/git/mine/private/school/4150/energyusage/PS12.py", line 43, in main
    just_n_result = energyusage.evaluate(just_n, x, printToScreen=False, energyOutput=True)
  File "/home/alex/.virtualenvs/4150-energyusage/lib/python3.7/site-packages/energyusage/evaluate.py", line 285, in evaluate
    printToScreen = printToScreen)
  File "/home/alex/.virtualenvs/4150-energyusage/lib/python3.7/site-packages/energyusage/evaluate.py", line 116, in energy
    files = utils.average_files(files)
  File "/home/alex/.virtualenvs/4150-energyusage/lib/python3.7/site-packages/energyusage/utils.py", line 32, in average_files
    file.process_average = statistics.mean(file.process)
  File "/usr/lib/python3.7/statistics.py", line 310, in mean
    raise StatisticsError('mean requires at least one data point')
statistics.StatisticsError: mean requires at least one data point
```

**Comment by klottick** [comment]
The input function is run as a process, then a loop repeatedly accesses the raplfiles until the process finishes. If the process finishes before the loop is ever entered, then the raplfiles are never updated and this error occurs. The required runtime is thus the time it takes between these lines:

`p.start() `
 `while(p.is_alive()):`

We have added an error message for cases where this issue occurs.
