### ISSUE TITLE
location logic is broken.

### ISSUE THREAD

**Issue by alexmherrmann** [responsibleproblemsolving/energy-usage#4]
`evaluate` fails the below code with the error below that

```python
from energyusage import evaluate
def new_counter():
	count = int(0)

	def to_return():
		# nonlocal is gross but it's needed here
		nonlocal count
		count += 1
		return count

	return to_return

if __name__ == '__main__':
	counter = new_counter()
	def work(n):
		for x in range(1, n**2):
			counter()

	secs, kwh, _ = evaluate(work, 5000, energyOutput=True, printToScreen=False)
```

```
Connected to pydev debugger (build 193.5233.102)
Process wattage:                                                     17.50 watts
--------------------------------------------------------------------------------
-------------------------------  Final Readings  -------------------------------
--------------------------------------------------------------------------------
Average baseline wattage:                                            15.96 watts
Average total wattage:                                               20.29 watts
Average process wattage:                                              4.33 watts
Process duration:                                                        0:00:26
Traceback (most recent call last):
  File "/home/alex/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/193.5233.102.plugins/python/helpers/pydev/pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/alex/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/193.5233.102.plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/alex/git/mine/private/school/4150/energyusage/broken_energyusage.py", line 22, in <module>
    secs, kwh, _ = evaluate(work, 5000, energyOutput=True, printToScreen=False)
  File "/home/alex/.virtualenvs/4150-energyusage/lib/python3.7/site-packages/energyusage/evaluate.py", line 315, in evaluate
    breakdown = energy_mix(location, year = year)
  File "/home/alex/.virtualenvs/4150-energyusage/lib/python3.7/site-packages/energyusage/evaluate.py", line 151, in energy_mix
    s = data[location]['mix'] # get state
KeyError: 'United States'

```

Because data is the list of US states instead of countries, but `locate.in_us` (or whatever the function is called) returns true for "United States", which is obviously not a US state, it tries to find "United States" in the list of US states. This fails.

The project could probably benefit from a few integration tests.

**Comment by alexmherrmann** [comment]
My workaround:

```python
def in_US(location):
    return (location in STATES)
```

**Comment by klottick** [comment]
We used your fix, thanks.
