### ISSUE TITLE
Problem after installing

### ISSUE THREAD

**Issue by CesarCastellonE** [responsibleproblemsolving/energy-usage#9]
Installed both from online and also tried downloading and installing locally.  Same error persists. Please Advise

asterix@obelix:~/Desktop$ python test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import energyusage
  File "/home/asterix/.local/lib/python2.7/site-packages/energyusage/__init__.py", line 2, in <module>
    from .evaluate import evaluate
  File "/home/asterix/.local/lib/python2.7/site-packages/energyusage/evaluate.py", line 25
    def energy(user_func, *args, powerLoss = 0.8, year, printToScreen):
                                         ^
SyntaxError: invalid syntax
asterix@obelix:~/Desktop$ python --version
Python 2.7.17

**Comment by wzziyao** [comment]
Thanks for letting us know the error! Please try using python3 instead of python when running your code.

**Comment by CesarCastellonE** [comment]
Hi!, installed python3 m and now it says

asterix@obelix:~/Desktop$ python3.7 test.py
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    energyusage.evaluate(recursive_fib, 40, pdf=True)
  File "/usr/local/lib/python3.7/site-packages/energyusage/evaluate.py", line 338, in evaluate
    utils.log("The energy-usage package only works on Linux kernels "
  File "/usr/local/lib/python3.7/site-packages/energyusage/utils.py", line 203, in log
    measurement = args[1]
IndexError: tuple index out of range


I am using the module on Linux Mint, VirtualBox Machine, is the module only for appliance machine or can be used on hypervisor machines?

**Comment by wzziyao** [comment]
The error points to the file "test.py," which is not in master. Make sure you are using the pip install version or the version from the master branch. 

The package only works on Linux kernels that have the RAPL interface and/or machines with an Nvidia GPU.
